version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ewire-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: ewire-app-image
    container_name: ewire-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: postgres

volumes:
  postgres_data:
